title: Pengxiao's Wiki
email: pxsongcs@163.com
description: >- # this means to ignore newlines until "baseurl:"
  "doing", building this blog is not the first thing for me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: placetaking
github_username:  Pengxixao

header_pages:
  - index.md
  - about.md
  - articals.md
  

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

html_author: Pengxiao Song
html_description: The web is Pengxiao Song's Wiki

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
