title: Pengxiao's Wiki
author: Song Pengxiao
email: pxsongcs@163.com
description:  # this means to ignore newlines until "baseurl:"
  # Pengxiao's
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: placetaking
github_username:  Pengxixao
  

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

google_analytics: UA-222809215-2

favicon: assets/icons/favicon-16x16.png
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
